### ISSUE TITLE
svelte を vue にコンバート

### ISSUE THREAD

**Issue by gsuzuki983** [hikaruchie/svelte-basic#5]

**Comment by harusys** [comment]
Vue3 Composition API がトレンドなので、その方式でマイグレする想定
軽くみても、参考ソースは以下あたりがイケてそう（Vite も使ってる）
https://vuejsexamples.com/a-simple-todo-list-made-with-vue-3-composition-api-and-vuex-4/

**Comment by harusys** [comment]
課題：Storybook の導入について考える

**Comment by harusys** [comment]
やること
* [ ] Vue サンプルに Storybook を導入する
* [ ] Vue サンプルの画面デザインを Svelte サンプルに寄せる

**Comment by harusys** [comment]
サンプルアプリはバージョンが古いため、Vue3 初期セットアップは以下を参考
https://qiita.com/frozenbonito/items/8a42f52e32ae82ffc9f2

**Comment by harusys** [comment]
参考にしたテンプレ
https://github.com/frozenbonito/quasar-vite-ts

これをベースで状態管理を Vuex に、デザインは Svelte サンプルに寄せる
